---
- name: Setup Flask App
  gather_facts: true
  hosts: all
  become: true

  vars:
    wdir: /home/devops-case-study
    venv: /home/venv
    reload: "{{ wdir }}/reload.sh > /dev/null 2>&1 &"
  tasks:
    - name: Install apt packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - git
        - python3-venv

    - name: Create virtualenv
      shell: python3 -m venv "{{ venv }}"

    - name: Upgrade pip
      pip:
        name: pip
        virtualenv: "{{ venv }}"
        state: forcereinstall

    - name: Install specified python requirements
      ansible.builtin.pip:
        requirements: "{{ wdir }}/requirements.txt"
        virtualenv: "{{ venv }}"

    - name: Start gunicorn
      shell: |
        chmod +x {{ wdir }}/reload.sh 
        {{ reload }}        
    
    - name: Start tracker
      shell: |
        chmod +x {{ wdir }}/tracker.sh 
        nohup {{ wdir }}/tracker.sh {{ wdir }} '{{ reload }}' > /dev/null 2>&1 &
