---
- name: Setup Flask App
  gather_facts: true
  hosts: all
  become: true
  vars:
    wdir: /home/devops-case-study
    venv: /home/venv
    mode: "{{ lookup('env','DEPLOY_MODE') }}"
  tasks:
    - name: Say hello
      debug:
        msg: "Hello World! - from {{ mode }}"

    - name: Install apt packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - git
        - python3-venv

    - name: Clone the repo from Github
      git:
        repo: https://github.com/PokerCoder/devops-case-study.git
        dest: "{{ wdir }}"
        clone: yes
        update: yes
      when: mode != 'LOCAL'

    - name: Create virtualenv
      shell: python3 -m venv "{{ venv }}"

    - name: Upgrade pip
      pip:
        name: pip
        virtualenv: "{{ venv }}"
        state: forcereinstall

    - name: Install specified python requirements
      ansible.builtin.pip:
        requirements: "{{ wdir }}/requirements.txt"
        virtualenv: "{{ venv }}"

    - name: Copy service file
      shell: cp {{ wdir }}/flask-app.service /etc/systemd/system/flask-app.service

    - name: Stop service to reload
      shell: systemctl stop flask-app

    - name: Start service
      shell: |
        systemctl daemon-reload
        systemctl start flask-app
